/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import animal from './animal';
import color from './color';
import date from './date';
import metadata from './metadata';
import word from './word';

/**
 * The locale data for the `cy` locale.
 *
 * - Language: Welsh
 * - Endonym: Cymraeg
 */
const cy: LocaleDefinition = {
  animal,
  color,
  date,
  metadata,
  word,
};

export default cy;
